spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/acuerdo}
  redis:
    url: ${REDIS_URL:redis://localhost:6379}

web3:
  nodeUrl: ${WEB3_NODE_URL:http://localhost:8545}
  log:
    listener:
      delay: ${WEB3_LOG_LISTENER_DELAY:1000}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:secret}
    expiration: ${SECURITY_JWT_EXPIRATION:86400000}