version: "3"

volumes:
  acuredo-mongo-data:

services:

  #todo
  #testrpc:

  mongodb:
    image: mongo:4.1
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - acuredo-mongo-data:/data/db

  server:
    build:
      context: ../server
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/acuerdo
      WEB3_NODE_URL: http://testrpc:8545
    ports:
      - 8080:8080

  webapp:
    build:
      context: ../dapp
    depends_on:
      - server
    ports:
      - 80:80


